### ISSUE TITLE
T21 should NOT be listed in `Condition (Source Text)`

### ISSUE THREAD

**Issue by lopierra** [include-dcc/inc-portal-model#10]
Problems:

- `T21` is listed in `Condition (Source Text)` with an associated MONDO code. `T21` is a status flag and should not be listed under Conditions. For any T21 patient in a non-KF dataset, I have already added a more DS specific subtype to their Conditions.

![image](https://user-images.githubusercontent.com/34149564/192674146-0525a861-6db0-4fac-be03-28d953452379.png)

**Comment by torstees** [comment]
I'm not entirely sure I'm following this entire issue but I'll try to address what I understand: 

1) The first issue is regarding the T21. That was mistakenly being loaded as a Condition and was fixed when JP pointed out the duplicate Down Syndrome occurrences. That change will go in at the next push, and I believe this issue will be addressed there. 

2) This appears to be a separate issue altogether but it's not entirely clear to me what you are suggesting. 

For KHOR, I'm not seeing anything except plain down syndrome diagnoses in the file @lopierra provided, which means that those BRI-DSR patients will only have the basic DS diagnoses. There are some "Mosaic trisomy 21" and 

Some Queries of interest: 

mosaic trisomy 21
https://include-api-fhir-service-qa.includedcc.org/Condition?_tag=BRI-DSC&code=MONDO:0700127   -- This yields no results
https://include-api-fhir-service-qa.includedcc.org/Condition?_tag=ABC-DS&code=MONDO:0700127    -- This yields 17 results
https://include-api-fhir-service-qa.includedcc.org/Condition?_tag=DSC&code=MONDO:0700127          -- This yields 75 results

complete trisomy 21
https://include-api-fhir-service-qa.includedcc.org/Condition?_tag=DSC&code=MONDO:0700030&_count=250   -- This yields more than 200 results
https://include-api-fhir-service-qa.includedcc.org/Condition?_tag=ABC-DS&code=MONDO:0700030&_count=250  -- This yields 318 results
https://include-api-fhir-service-qa.includedcc.org/Condition?_tag=BRI-DSR&code=MONDO:0700030&_count=250  -- This yields zero results

I'm not sure how those conditions that are showing up in the queries above look in the portal but it may be that the issue is only with the KHOR data. @jthib077 if you could confirm this or advise me on what I may need to fix for them to show up correctly.

**Comment by jthib077** [comment]
For point #2, it is a portal/MONDO issue. We fetch all the MONDO codes available in a obo file format that the MONDO team releases. We searched in our current version for the MONDO codes missing, complete trisomy, mosaic, vitamin d deficiency, etc. and they were not appearing. 

We usually download this file: http://purl.obolibrary.org/obo/mondo.obo but it does not seem to be loading so this issue will need to be fixed post ABC-DS demo.

**Comment by lopierra** [comment]
@torstees Khor only has plain DS diagnoses (MONDO:0008608)

And sorry, I thought these were a related issue. Will be more granular going forward!

**Comment by lopierra** [comment]
Started new issue #14  for the missing MONDO codes & removed that topic from this issue

**Comment by torstees** [comment]
> For point #2, it is a portal/MONDO issue. We fetch all the MONDO codes available in a obo file format that the MONDO team releases. We searched in our current version for the MONDO codes missing, complete trisomy, mosaic, vitamin d deficiency, etc. and they were not appearing.
> 
> We usually download this file: http://purl.obolibrary.org/obo/mondo.obo but it does not seem to be loading so this issue will need to be fixed post ABC-DS demo.

@jthib077 The codes in the FHIR Codings should be complete and the display should have been derived from the MONDO display. Are you not using that information?
