### ISSUE TITLE
Incorrect `Family Unit` for some participants

### ISSUE THREAD

**Issue by lopierra** [include-dcc/inc-portal-model#12]
DSC 3593 and 3591 are siblings - Family Unit for those two should be `Other`, not `Proband-only`. The clinical data download shows the correct Family ID (3591), and downloading "Participant and Families" for either 3591 or 3593 returns both, so they are correctly linked - just the Family Unit is wrong.

A similar thing is happening with ABC-DS, e.g. 10202 & 10135 are siblings with Family ID = 10135, but Family Type should be `Other` instead of `Proband-only`

**Comment by jthib077** [comment]
This may be a portal issue. We will take a look but it might be a larger issue that may require more time to solve

**Comment by torstees** [comment]
I may be mistaken, but I believe the Family Type is driven by the group membership. If so, it is correct in FHIR for the DSC pair: 

https://include-api-fhir-service-qa.includedcc.org/Patient/624416 Subject 3593
https://include-api-fhir-service-qa.includedcc.org/Patient/624406 Subject 3591
https://include-api-fhir-service-qa.includedcc.org/Group?member=Patient/624416

That group query returns 2 groups. The first contains all members of the DSC study and the second contains 2 members. 

If the source of these family types is the generic family relationship that I didn't do for this load, it can be resolved easily enough.

**Comment by jthib077** [comment]
I think ideally we should pull it from FHIR but it seems like the KF Studies don't have the system defining the family type. Perhaps because this family type information was not available in the KF Data Service in the first place. I think we can temporarily work fix the logic on our end. We will try to get it done by Monday but its possible we will be too tight on time. 

system": ["https://nih-ncpi.github.io/ncpi-fhir-ig/CodeSystem/data-dictionary/BRI-DSR/participant/family_type"]

**Comment by lopierra** [comment]
This is fixed, although in future we should reconcile whether Family Type should be inferred or inputted in the Family Type field of the data.
